### ISSUE TITLE
Maybe there is need to make fix in non_max_suppression

### ISSUE THREAD

**Issue by igor-yusupov** [robertknight/rten#176]
Hi! Thank you so much for providing an example of yolov8.
I run it and it found 21 objects in image and it seems to be much more than should be.

Attached images after inference with yolov8-rten and original yolo:
![image](https://github.com/robertknight/rten/assets/47746505/5a8d136f-2f0d-495f-a4ad-5e48754c1071)
![bus](https://github.com/robertknight/rten/assets/47746505/d7554556-1bf3-40a5-8964-2aa779f1a883)

**Comment by robertknight** [comment]
Thanks for the bug report. There was a really dumb bug where the bottom/right coordinates of boxes got mixed up. Depending on the location of the object in an image, this could cause overlap to be missed.
