### ISSUE TITLE
training in rten ?

### ISSUE THREAD

**Issue by zeroexcuses** [robertknight/rten#296]
probably no, but thought I'm ask anyway:

is there a way to do TRAINING in rten? the use case is pedagogical , example: training a MNIST classifier directly in browser, instead of needing a server side component

**Comment by robertknight** [comment]
Unfortunately, no. RTen only supports inference. On a technical level it only implements the forwards pass for operations (matmul, convolution etc.) and not the backwards pass that back-propagates gradients.

**Comment by zeroexcuses** [comment]
Thanks!
