### ISSUE TITLE
Tensor from ndarray

### ISSUE THREAD

**Issue by igor-yusupov** [robertknight/rten#41]
Is it possible to get Tensor from ndarray Array?

**Comment by robertknight** [comment]
Yes, it is possible to convert from one to the other. I put some code samples in https://gist.github.com/robertknight/ad54cc02a79d0824e6e576401d3d433e. I'm going to try and make this easier in future as part of https://github.com/robertknight/rten/issues/37.

For the use case of preparing some data with ndarray, running a model and getting the results back into an ndarray for post-processing, the flow would look something like:

1. Load data into ndarray array and do whatever preprocessing etc. you need.
2. Create a view of that array as an `NdTensorView` and pass to `Model::run`
3. Take the output from `Model::run` and convert either to an `ArrayView` or `Array`.

**Comment by igor-yusupov** [comment]
It sounds great! I'll be looking forward to it. Thank you
