### ISSUE TITLE
Model conversion tools should be a pip-installable Python package

### ISSUE THREAD

**Issue by robertknight** [robertknight/rten#45]
Using the model conversion tools currently takes several steps ([notes](https://github.com/robertknight/rten#getting-started)):

1. Clone the repository
2. Set up a virtualenv
3. Install dependencies
4. Run the conversion script, specifying the path

It would be more convenient, especially when providing instructions in other projects, if the conversion tools were a pip-installable package. This would enable the process to look something like:

```sh
$ pip install rten-tools
$ rten convert model.onnx
```

This would also enable the conversion tools to be used more easily in automated processes (CI pipelines etc.)

**Comment by igor-yusupov** [comment]
Can I take the task? It seems to be enough to add the setup.py file to the tools directory.

**Comment by robertknight** [comment]
I think the conversion tool should be separated out into a separate directory as a first step, structured as a modern Python package, so that it can express just its own dependencies and other metadata properly. The `tools/requirements.txt` file contains a bunch of large dependencies (eg. PyTorch) which are not needed for the conversion tool, but are used by some of the other scripts.

This could look something along the lines of:

```
rten-convert/
  README.md
  pyproject.toml
  ...
  rten_convert/
    __init__.py
    converter.py
```

The description of this issue suggests the converter should be runnable with `rten convert ...`. The `rten` binary name is already used by the `rten-cli` crate for the Rust tool that inspects and runs models, so it'll need to be something else (eg. `rten-convert`).

**Comment by igor-yusupov** [comment]
I added a PR: https://github.com/robertknight/rten/pull/53

Ready to add/change something according to the comments)

**Comment by robertknight** [comment]
One thing that needs to be clarified before I publish the tool is the version compatibility - which versions of the `rten` crate can load a model produced with a particular version of the converter. I think the easiest thing is to give the converter the same version number as the `rten` library and publish updates to both at the same time. Then the policy is that eg. rten-convert v0.5 produces models that can be loaded by rten v0.5 or any later version.

**Comment by igor-yusupov** [comment]
Yeah, that seems like it would be more user friendly.

**Comment by igor-yusupov** [comment]
I've updated the version.

Maybe it's still worth setting up the dependency versions? That is, set up the version for onnx, numpy, etc.? Or is it ok if the latest version of the library is always used or the one installed locally?

**Comment by robertknight** [comment]
> Maybe it's still worth setting up the dependency versions? That is, set up the version for onnx, numpy, etc.? Or is it ok if the latest version of the library is always used or the one installed locally?

I think we probably want to specify minimum dependency versions, so that installing `rten-convert` ensures that a new-enough version of onnx, numpy etc. is installed, but allows newer versions to be installed in the same virtualenv. I'd take the current stable versions of these libraries as the initial requirement.
