### ISSUE TITLE
Transformer inference error

### ISSUE THREAD

**Issue by igor-yusupov** [robertknight/rten#46]
I tried to run inference with encoder from transformer model and got error: `Result::unwrap()` on an `Err` value: OperatorError { name: "/encoder/layers.0/self_attn/Gather_3", error: InvalidValue("Entry in `indices` is out of range") }

model info: https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html
weights: https://www.dropbox.com/scl/fi/bf3wlxhzhl1fg2o2ha1yu/encoder.rten?rlkey=7mi8txp73eyqbwqlb05jcpxxq&dl=0

**Comment by igor-yusupov** [comment]
Example code:

```
use ndarray::{Array, ArrayView, Dim, Dimension, Ix, StrideShape};
use rten::Model;
use rten_tensor::prelude::*;
use rten_tensor::{AsView, NdTensorView};
use std::fs;

fn as_ndtensor_view<'a, T, const N: usize>(
    view: ArrayView<'a, T, Dim<[Ix; N]>>,
) -> Option<NdTensorView<'a, T, N>>
where
    Dim<[Ix; N]>: Dimension,
{
    view.to_slice().map(|slice| {
        let shape: [usize; N] = view.shape().try_into().unwrap();
        NdTensorView::from_data(shape, slice)
    })
}

fn as_array_view<'a, T, const N: usize>(
    view: NdTensorView<'a, T, N>,
) -> Option<ArrayView<'a, T, Dim<[Ix; N]>>>
where
    Dim<[Ix; N]>: Dimension,
    [usize; N]: Into<StrideShape<Dim<[Ix; N]>>>,
{
    view.data()
        .map(|data| ArrayView::from_shape(view.shape(), data).unwrap())
}

fn main() {
    let encoder_path = "encoder_en_ja.rten";
    let encoder = Model::load(&fs::read(encoder_path).unwrap()).unwrap();
    let src = Array::from_shape_vec(
        (9, 1),
        vec![1, 34543, 49935, 1242, 775, 81, 1931, 49936, 2]
            .iter()
            .map(|&x| x as i32)
            .collect(),
    )
    .unwrap();
    let src = as_ndtensor_view(src.view()).unwrap().to_tensor();
    let memory = encoder.run_one(src.view().into(), None).unwrap();
}

```

**Comment by robertknight** [comment]
Thanks for the bug report. I was able to reproduce with:

```
cargo run -r -p rten-cli -- encoder.rten
```

Part of the model had something that looked like it came from `tensor.shape[-1]` and the index bounds check didn't account for negative indices, although the implementation supported them.

**Comment by igor-yusupov** [comment]
Thank you for operative PR!
I tried to run example code with last commit and it seems that new error occurs:
```
called `Result::unwrap()` on an `Err` value: OperatorError { name: "/src_tok_emb/embedding/Gather", error: InvalidValue("Entry in `indices` is out of range") }
```

I set up like that:
```
rten = {git = "https://github.com/robertknight/rten.git"}
rten-tensor = {git = "https://github.com/robertknight/rten.git"}
```

**Comment by igor-yusupov** [comment]
I can also attach onnx weights if needed

**Comment by igor-yusupov** [comment]
It seems to be my fault. I tried to set up tokens = vec![1, 2, 3, 4, 5, 6, 7, 8, 9] and it is OK.
Sorry for misunderstanding.

Now I will try to run my pipeline with rten and will check if it works correctly. Thank you again!
